export const moc = [{"name":"Nezlobnaya","description":"Russia"},
{"name":"Leleque","description":"Argentina"},
{"name":"Barusuda","description":"Indonesia"},
{"name":"Pereira","description":"Portugal"},
{"name":"Soritor","description":"Peru"},
{"name":"Cikuya","description":"Indonesia"},
{"name":"El Plan","description":"Honduras"},
{"name":"Ho","description":"Ghana"},
{"name":"Jabon","description":"Indonesia"},
{"name":"Opatovice nad Labem","description":"Czech Republic"},
{"name":"Daying","description":"China"},
{"name":"Badeggi","description":"Nigeria"},
{"name":"Souto da Casa","description":"Portugal"},
{"name":"Matagbak","description":"Philippines"},
{"name":"Yanagawamachi-saiwaichō","description":"Japan"},
{"name":"Sovetskaya","description":"Russia"},
{"name":"Erdenet","description":"Mongolia"},
{"name":"Charneca da Cotovia","description":"Portugal"},
{"name":"Bweyogerere","description":"Uganda"},
{"name":"Arles","description":"France"},
{"name":"Kopayhorod","description":"Ukraine"},
{"name":"Santa Cruz","description":"Philippines"},
{"name":"Pochep","description":"Russia"},
{"name":"Nong Kung Si","description":"Thailand"},
{"name":"Saint-Jean-de-Védas","description":"France"},
{"name":"Padre Paraíso","description":"Brazil"},
{"name":"Cabouco","description":"Portugal"},
{"name":"Otwock","description":"Poland"},
{"name":"Bailu","description":"China"},
{"name":"Kinsale","description":"Ireland"},
{"name":"Uruguaiana","description":"Brazil"},
{"name":"Lopandino","description":"Russia"},
{"name":"Mugumu","description":"Tanzania"},
{"name":"Pánormos","description":"Greece"},
{"name":"Nizhnyaya Tura","description":"Russia"},
{"name":"Anfusi","description":"China"},
{"name":"Kalimati","description":"Indonesia"},
{"name":"Strelitsa","description":"Russia"},
{"name":"Bansko","description":"Bulgaria"},
{"name":"Santa Helena de Goiás","description":"Brazil"},
{"name":"Lincheng","description":"China"},
{"name":"Luotang","description":"China"},
{"name":"Alfta","description":"Sweden"},
{"name":"Croix","description":"France"},
{"name":"Nahāvand","description":"Iran"},
{"name":"Situ","description":"China"},
{"name":"Kertasari","description":"Indonesia"},
{"name":"Namora","description":"Peru"},
{"name":"Ulety","description":"Russia"},
{"name":"Kamaishi","description":"Japan"},
{"name":"Qal‘eh-ye Khvājeh","description":"Iran"},
{"name":"Bokoro","description":"Chad"},
{"name":"Krajan Atas Suger Lor","description":"Indonesia"},
{"name":"Maia","description":"Portugal"},
{"name":"El Refugio","description":"Mexico"},
{"name":"Baddomalhi","description":"Pakistan"},
{"name":"São Bento do Sul","description":"Brazil"},
{"name":"Alor Setar","description":"Malaysia"},
{"name":"Lees Summit","description":"United States"},
{"name":"Hāgere Hiywet","description":"Ethiopia"},
{"name":"Tuxi","description":"China"},
{"name":"Merapit","description":"Indonesia"},
{"name":"Barreiros","description":"Portugal"},
{"name":"Pandanwangi","description":"Indonesia"},
{"name":"Kawakawa","description":"New Zealand"},
{"name":"Rakaia","description":"New Zealand"},
{"name":"Yupiltepeque","description":"Guatemala"},
{"name":"Alīābad","description":"Pakistan"},
{"name":"Stockton","description":"United States"},
{"name":"Madrid","description":"Colombia"},
{"name":"Kristiansand S","description":"Norway"},
{"name":"Patpata Segundo","description":"Philippines"},
{"name":"Huangtukuang","description":"China"},
{"name":"Cordon","description":"Philippines"},
{"name":"Johor Bahru","description":"Malaysia"},
{"name":"Bachuan","description":"China"},
{"name":"20 de Noviembre","description":"Mexico"},
{"name":"Watulumbung","description":"Indonesia"},
{"name":"Maple Ridge","description":"Canada"},
{"name":"Sabana Iglesia","description":"Dominican Republic"},
{"name":"Rodotópi","description":"Greece"},
{"name":"Senador Pompeu","description":"Brazil"},
{"name":"Santa Bárbara de Padrões","description":"Portugal"},
{"name":"Anjihai","description":"China"},
{"name":"Västerås","description":"Sweden"},
{"name":"Roissy Charles-de-Gaulle","description":"France"},
{"name":"Osiek","description":"Poland"},
{"name":"Songshan","description":"China"},
{"name":"Balading","description":"Philippines"},
{"name":"Rancaseneng","description":"Indonesia"},
{"name":"Shigongqiao","description":"China"},
{"name":"Lunao","description":"Philippines"},
{"name":"Ribeirinha","description":"Portugal"},
{"name":"Somerset East","description":"South Africa"},
{"name":"Hangji","description":"China"},
{"name":"Jhang Sadr","description":"Pakistan"},
{"name":"Tycheró","description":"Greece"},
{"name":"Dalonghua","description":"China"},
{"name":"Botigues","description":"Philippines"},
{"name":"Североморск-3","description":"Russia"},
{"name":"Semeljci","description":"Croatia"},
{"name":"Yongping","description":"China"},
{"name":"Songnim","description":"North Korea"},
{"name":"Zhongba","description":"China"},
{"name":"Mensalong","description":"Indonesia"},
{"name":"Gesing","description":"Indonesia"},
{"name":"Nīkshahr","description":"Iran"},
{"name":"Quatro Barras","description":"Brazil"},
{"name":"Puqi","description":"China"},
{"name":"Trois-Rivières","description":"Canada"},
{"name":"Petrovskaya","description":"Russia"},
{"name":"Riung","description":"Indonesia"},
{"name":"Sukoanyar","description":"Indonesia"},
{"name":"Rimus","description":"Philippines"},
{"name":"Baru","description":"Indonesia"},
{"name":"Cigagade","description":"Indonesia"},
{"name":"Krajan Timur Suger Kidul","description":"Indonesia"},
{"name":"Avignon","description":"France"},
{"name":"Lubumbashi","description":"Democratic Republic of the Congo"},
{"name":"Kototujuh","description":"Indonesia"},
{"name":"Tongchuan","description":"China"},
{"name":"Lidong","description":"China"},
{"name":"Liangshan","description":"China"},
{"name":"Ambositra","description":"Madagascar"},
{"name":"Fengxizhai","description":"China"},
{"name":"Ronggui","description":"China"},
{"name":"São Sebastião","description":"Brazil"},
{"name":"Soho","description":"Indonesia"},
{"name":"Japeri","description":"Brazil"},
{"name":"Połomia","description":"Poland"},
{"name":"Ḩammām Damt","description":"Yemen"},
{"name":"Requião","description":"Portugal"},
{"name":"Kula","description":"Serbia"},
{"name":"Dagang","description":"China"},
{"name":"Madrid","description":"Spain"},
{"name":"Novokuz’minki","description":"Russia"},
{"name":"Zheleznogorsk","description":"Russia"},
{"name":"Banawang","description":"Philippines"},
{"name":"Seixezelo","description":"Portugal"},
{"name":"Mólos","description":"Greece"},
{"name":"Mary","description":"Turkmenistan"},
{"name":"Recreio","description":"Brazil"},
{"name":"Ipoh","description":"Malaysia"},
{"name":"Rancabuaya","description":"Indonesia"},
{"name":"Balugo","description":"Philippines"},
{"name":"Ogwashi-Uku","description":"Nigeria"},
{"name":"Lanas","description":"Philippines"},
{"name":"Saparua","description":"Indonesia"},
{"name":"Igoumenítsa","description":"Greece"},
{"name":"Semiluki","description":"Russia"},
{"name":"Leloboko","description":"Indonesia"},
{"name":"Rychtal","description":"Poland"},
{"name":"Jiantian","description":"China"},
{"name":"Sobrosa","description":"Portugal"},
{"name":"Nueva Vida Sur","description":"Philippines"},
{"name":"Alkmaar","description":"Netherlands"},
{"name":"Ceelbuur","description":"Somalia"},
{"name":"Port Maria","description":"Jamaica"},
{"name":"Cha-am","description":"Thailand"},
{"name":"Tondano","description":"Indonesia"},
{"name":"Liborina","description":"Colombia"},
{"name":"Gongjiahe","description":"China"},
{"name":"Ríohacha","description":"Colombia"},
{"name":"Rohia","description":"Tunisia"},
{"name":"Barurao","description":"Philippines"},
{"name":"Katrineholm","description":"Sweden"},
{"name":"Leiden","description":"Netherlands"},
{"name":"Avanca","description":"Portugal"},
{"name":"Prince Albert","description":"South Africa"},
{"name":"Yelizavetino","description":"Russia"},
{"name":"Villefontaine","description":"France"},
{"name":"Otradnoye","description":"Russia"},
{"name":"Montréal-Ouest","description":"Canada"},
{"name":"Jolo","description":"Philippines"},
{"name":"Ngembo","description":"Indonesia"},
{"name":"Luotang","description":"China"},
{"name":"Coja","description":"Portugal"},
{"name":"Prince Rupert","description":"Canada"},
{"name":"Pospelikha","description":"Russia"},
{"name":"Massenya","description":"Chad"},
{"name":"La Carlota","description":"Philippines"},
{"name":"Ilopango","description":"El Salvador"},
{"name":"Moita da Roda","description":"Portugal"},
{"name":"Tinogasta","description":"Argentina"},
{"name":"Águas Belas","description":"Brazil"},
{"name":"Gang","description":"Philippines"},
{"name":"Laidian","description":"China"},
{"name":"San Miguel","description":"Peru"},
{"name":"Naḩḩālīn","description":"Palestinian Territory"},
{"name":"Peabiru","description":"Brazil"},
{"name":"Isla","description":"Philippines"},
{"name":"Jiulongshan","description":"China"},
{"name":"Longos","description":"Philippines"},
{"name":"Savé","description":"Benin"},
{"name":"Ogoja","description":"Nigeria"},
{"name":"Popielów","description":"Poland"},
{"name":"Béboto","description":"Chad"},
{"name":"Sipeng","description":"China"},
{"name":"Wakema","description":"Myanmar"},
{"name":"Parelhas","description":"Brazil"},
{"name":"Ar Ramāḑīn","description":"Palestinian Territory"},
{"name":"Sharan","description":"Russia"},
{"name":"San Diego","description":"United States"},
{"name":"Zhengcun","description":"China"},
{"name":"Jīwani","description":"Pakistan"},
{"name":"Malausma Kidul","description":"Indonesia"},
{"name":"Al ‘Ashshah","description":"Yemen"},
{"name":"Qiandeng","description":"China"},
{"name":"Shangzhang","description":"China"},
{"name":"Fucheng","description":"China"},
{"name":"Chiscas","description":"Colombia"},
{"name":"Gizel’","description":"Russia"},
{"name":"Caimitillo","description":"Panama"},
{"name":"Penha","description":"Brazil"},
{"name":"Nässjö","description":"Sweden"},
{"name":"Khombole","description":"Senegal"},
{"name":"Sakaraha","description":"Madagascar"},
{"name":"Zátor","description":"Czech Republic"},
{"name":"Rueil-Malmaison","description":"France"},
{"name":"Bordeaux","description":"France"},
{"name":"Serang","description":"Indonesia"},
{"name":"Erandique","description":"Honduras"},
{"name":"Xilian","description":"China"},
{"name":"Dimiao","description":"Philippines"},
{"name":"Santa Rita","description":"Bolivia"},
{"name":"Widuchowa","description":"Poland"},
{"name":"Loreto","description":"Philippines"},
{"name":"Maltahöhe","description":"Namibia"},
{"name":"Ar Rudayyif","description":"Tunisia"},
{"name":"Quilpué","description":"Chile"},
{"name":"Kanekomachi","description":"Japan"},
{"name":"Tubigan","description":"Philippines"},
{"name":"Älvdalen","description":"Sweden"},
{"name":"Mozelos","description":"Portugal"},
{"name":"Lawrenceville","description":"United States"},
{"name":"Dūrā al Qar‘","description":"Palestinian Territory"},
{"name":"Sysert’","description":"Russia"},
{"name":"Baishan","description":"China"},
{"name":"Ipoh","description":"Malaysia"},
{"name":"Sharga","description":"Mongolia"},
{"name":"Le Mans","description":"France"},
{"name":"Itaituba","description":"Brazil"},
{"name":"Huancapallac","description":"Peru"},
{"name":"Angers","description":"France"},
{"name":"Dongjiao","description":"China"},
{"name":"Embalse","description":"Argentina"},
{"name":"Aūa","description":"American Samoa"},
{"name":"Gashua","description":"Nigeria"},
{"name":"Horad Smalyavichy","description":"Belarus"},
{"name":"Chizhou","description":"China"},
{"name":"El Alamo","description":"Mexico"},
{"name":"Dambarta","description":"Nigeria"},
{"name":"Mingjiu","description":"China"},
{"name":"Yermolayevo","description":"Russia"},
{"name":"Hà Đông","description":"Vietnam"},
{"name":"Diamantina","description":"Brazil"},
{"name":"Kochani","description":"Macedonia"},
{"name":"Belz","description":"Ukraine"},
{"name":"Yandun","description":"China"},
{"name":"Desnogorsk","description":"Russia"},
{"name":"Shizunai-furukawachō","description":"Japan"},
{"name":"Tazhuang","description":"China"},
{"name":"Kumane","description":"Serbia"},
{"name":"Portelinha","description":"Portugal"},
{"name":"Kuala Lumpur","description":"Malaysia"},
{"name":"Tucheng","description":"China"},
{"name":"Yunping","description":"China"},
{"name":"Huandiqiao","description":"China"},
{"name":"Idritsa","description":"Russia"},
{"name":"Maceda","description":"Portugal"},
{"name":"Changqing","description":"China"},
{"name":"Nambalan","description":"Philippines"},
{"name":"Rio Branco","description":"Brazil"},
{"name":"Shuanggang","description":"China"},
{"name":"Non Sila","description":"Thailand"},
{"name":"Narsaq","description":"Greenland"},
{"name":"Colorado Springs","description":"United States"},
{"name":"Sandakan","description":"Malaysia"},
{"name":"Dolo","description":"Philippines"},
{"name":"Dairiti","description":"Indonesia"},
{"name":"Magitang","description":"China"},
{"name":"Prokuplje","description":"Serbia"},
{"name":"Baishigou","description":"China"},
{"name":"Mahébourg","description":"Mauritius"},
{"name":"Montemor-o-Velho","description":"Portugal"},
{"name":"Yuxi","description":"China"},
{"name":"Jiumen","description":"China"},
{"name":"Nyandoma","description":"Russia"},
{"name":"Daejeon","description":"South Korea"},
{"name":"Wangdain","description":"China"},
{"name":"Pokachi","description":"Russia"},
{"name":"Dingle","description":"Philippines"},
{"name":"Khiliomódhi","description":"Greece"},
{"name":"Khallat Şāliḩ","description":"Palestinian Territory"},
{"name":"Guisijan","description":"Philippines"},
{"name":"Igboho","description":"Nigeria"},
{"name":"Tân Hiệp","description":"Vietnam"},
{"name":"Rio Branco do Sul","description":"Brazil"},
{"name":"Kastsyukovichy","description":"Belarus"},
{"name":"Chengnan","description":"China"},
{"name":"Örebro","description":"Sweden"},
{"name":"Milton","description":"United Kingdom"},
{"name":"Skole","description":"Ukraine"},
{"name":"Khantaghy","description":"Kazakhstan"},
{"name":"Gamboula","description":"Central African Republic"},
{"name":"Yanping","description":"China"},
{"name":"Aconibe","description":"Equatorial Guinea"},
{"name":"Montgomery","description":"United States"},
{"name":"Salam","description":"Indonesia"},
{"name":"Fenghuanglu","description":"China"},
{"name":"Tolstoy-Yurt","description":"Russia"},
{"name":"Passal","description":"Portugal"},
{"name":"Chengnan","description":"China"},
{"name":"Mangaldan","description":"Philippines"},
{"name":"Yihe","description":"China"},
{"name":"Blimbing","description":"Indonesia"},
{"name":"Uthai Thani","description":"Thailand"},
{"name":"Bantog","description":"Philippines"},
{"name":"Xinshi","description":"China"},
{"name":"San Lorenzo de Esmeraldas","description":"Ecuador"},
{"name":"Isiro","description":"Democratic Republic of the Congo"},
{"name":"Jabal os Saraj","description":"Afghanistan"},
{"name":"Al Muţayrifī","description":"Saudi Arabia"},
{"name":"Curpahuasi","description":"Peru"},
{"name":"San Pedro","description":"Bolivia"},
{"name":"Ḩājī Khēl","description":"Afghanistan"},
{"name":"Douane","description":"Tunisia"},
{"name":"Nioki","description":"Democratic Republic of the Congo"},
{"name":"Néma","description":"Mauritania"},
{"name":"Thị Trấn Mường Tè","description":"Vietnam"},
{"name":"Perené","description":"Peru"},
{"name":"København","description":"Denmark"},
{"name":"Ngrambitan","description":"Indonesia"},
{"name":"Houmt Souk","description":"Tunisia"},
{"name":"Hegeng","description":"China"},
{"name":"Örnsköldsvik","description":"Sweden"},
{"name":"Heba","description":"China"},
{"name":"Araouane","description":"Mali"},
{"name":"Chowki Jamali","description":"Pakistan"},
{"name":"Gazimurskiy Zavod","description":"Russia"},
{"name":"San Vicente","description":"Philippines"},
{"name":"Guolemude","description":"China"},
{"name":"Stare Miasto","description":"Poland"},
{"name":"Talisayan","description":"Philippines"},
{"name":"Lederaba","description":"Indonesia"},
{"name":"Červená Voda","description":"Czech Republic"},
{"name":"Penghua","description":"China"},
{"name":"Ninove","description":"Belgium"},
{"name":"Al Bāriqīyah","description":"Syria"},
{"name":"Xiangfeng","description":"China"},
{"name":"Libertador General San Martín","description":"Argentina"},
{"name":"Carpentras","description":"France"},
{"name":"Hua Hin","description":"Thailand"},
{"name":"Rudziczka","description":"Poland"},
{"name":"Desa Werasari","description":"Indonesia"},
{"name":"Zhoukou","description":"China"},
{"name":"Saint-Sauveur","description":"Canada"},
{"name":"Asímion","description":"Greece"},
{"name":"Krzeszów","description":"Poland"},
{"name":"Moa","description":"Cuba"},
{"name":"Stockholm","description":"Sweden"},
{"name":"Allanridge","description":"South Africa"},
{"name":"Taiyu","description":"China"},
{"name":"Banjar Bau Kawan","description":"Indonesia"},
{"name":"Quezon","description":"Philippines"},
{"name":"Sukamahi Satu","description":"Indonesia"},
{"name":"Bago","description":"Indonesia"},
{"name":"Astorga","description":"Brazil"},
{"name":"Santo Antônio de Posse","description":"Brazil"},
{"name":"Haukipudas","description":"Finland"},
{"name":"Benhong","description":"China"},
{"name":"Siquanpu","description":"China"},
{"name":"Repušnica","description":"Croatia"},
{"name":"Lang Suan","description":"Thailand"},
{"name":"Asan-Maina Village","description":"Guam"},
{"name":"Obolo-Eke (1)","description":"Nigeria"},
{"name":"Chahe","description":"China"},
{"name":"Kyzylorda","description":"Kazakhstan"},
{"name":"Lingqiao","description":"China"},
{"name":"Nangkapayung","description":"Indonesia"},
{"name":"Bahui","description":"China"},
{"name":"Sơn Tịnh","description":"Vietnam"},
{"name":"Gobernador Ingeniero Valentín Virasoro","description":"Argentina"},
{"name":"Puerto Castilla","description":"Honduras"},
{"name":"Waco","description":"United States"},
{"name":"Podstrana","description":"Croatia"},
{"name":"Oropesa","description":"Peru"},
{"name":"Coruripe","description":"Brazil"},
{"name":"Sagopshi","description":"Russia"},
{"name":"Monaragala","description":"Sri Lanka"},
{"name":"Gesing","description":"Indonesia"},
{"name":"Berlin","description":"Germany"},
{"name":"Nambak Tengah","description":"Indonesia"},
{"name":"Ewirgol","description":"China"},
{"name":"Stadtbredimus","description":"Luxembourg"},
{"name":"Porsgrunn","description":"Norway"},
{"name":"Ikoma","description":"Japan"},
{"name":"Wulong","description":"China"},
{"name":"Västerås","description":"Sweden"},
{"name":"Vigo","description":"Philippines"},
{"name":"Dongtian","description":"China"},
{"name":"Corralito","description":"Argentina"},
{"name":"Lizhuangzi","description":"China"},
{"name":"Lusacan","description":"Philippines"},
{"name":"Suodenniemi","description":"Finland"},
{"name":"Sandaohezi","description":"China"},
{"name":"Nipawin","description":"Canada"},
{"name":"Garoua","description":"Cameroon"},
{"name":"Huanglian","description":"China"},
{"name":"Kota Kinabalu","description":"Malaysia"},
{"name":"Piritiba","description":"Brazil"},
{"name":"Cardal","description":"Uruguay"},
{"name":"Ngaruawahia","description":"New Zealand"},
{"name":"Cirangkong","description":"Indonesia"},
{"name":"Sengkerang Tiga","description":"Indonesia"},
{"name":"Qacha’s Nek","description":"Lesotho"},
{"name":"Xianshuigu","description":"China"},
{"name":"Imbang","description":"Philippines"},
{"name":"Louisville","description":"United States"},
{"name":"Haolin","description":"China"},
{"name":"La Roche-sur-Yon","description":"France"},
{"name":"Zhuangta","description":"China"},
{"name":"Jagistay","description":"China"},
{"name":"Kedungkrajan","description":"Indonesia"},
{"name":"Rostock","description":"Germany"},
{"name":"Chom Bueng","description":"Thailand"},
{"name":"Łubnice","description":"Poland"},
{"name":"Gancheng","description":"China"},
{"name":"Ängelholm","description":"Sweden"},
{"name":"Předklášteří","description":"Czech Republic"},
{"name":"Kabinda","description":"Democratic Republic of the Congo"},
{"name":"Zhongdong","description":"China"},
{"name":"Benchu","description":"China"},
{"name":"Lutowiska","description":"Poland"},
{"name":"Merida","description":"Philippines"},
{"name":"Hagerstown","description":"United States"},
{"name":"Annacotty","description":"Ireland"},
{"name":"Rzhev","description":"Russia"},
{"name":"Trancas","description":"Argentina"},
{"name":"Pueai Noi","description":"Thailand"},
{"name":"Shenzhong","description":"China"},
{"name":"Bombu","description":"Indonesia"},
{"name":"Yili","description":"China"},
{"name":"Xiaping","description":"China"},
{"name":"Tailing","description":"China"},
{"name":"Guadalupe","description":"Mexico"},
{"name":"Khānewāl","description":"Pakistan"},
{"name":"Słubice","description":"Poland"},
{"name":"Humble","description":"United States"},
{"name":"Gostilitsy","description":"Russia"},
{"name":"Tangshan","description":"China"},
{"name":"Wschowa","description":"Poland"},
{"name":"Novokuybyshevsk","description":"Russia"},
{"name":"Gagah","description":"Indonesia"},
{"name":"Zheleznogorsk","description":"Russia"},
{"name":"Martyush","description":"Russia"},
{"name":"Al Ain","description":"United Arab Emirates"},
{"name":"Bacheng","description":"China"},
{"name":"Kipen’","description":"Russia"},
{"name":"Nossa Senhora da Glória","description":"Brazil"},
{"name":"Pluak Daeng","description":"Thailand"},
{"name":"Unecha","description":"Russia"},
{"name":"Mrągowo","description":"Poland"},
{"name":"Uritsk","description":"Russia"},
{"name":"Batelov","description":"Czech Republic"},
{"name":"Soubré","description":"Ivory Coast"},
{"name":"Raciąż","description":"Poland"},
{"name":"Villa Francisca","description":"Dominican Republic"},
{"name":"Ashtarak","description":"Armenia"},
{"name":"Novi Karlovci","description":"Serbia"},
{"name":"Dama","description":"China"},
{"name":"Palhais","description":"Portugal"},
{"name":"Nanyang","description":"China"},
{"name":"Nantes","description":"France"},
{"name":"Casal do Sapo","description":"Portugal"},
{"name":"Det Udom","description":"Thailand"},
{"name":"Marsabit","description":"Kenya"},
{"name":"Lichengdao","description":"China"},
{"name":"Morón","description":"Cuba"},
{"name":"Pacaycasa","description":"Peru"},
{"name":"Kentville","description":"Canada"},
{"name":"Kukuluk","description":"Indonesia"},
{"name":"Aţ Ţafīlah","description":"Jordan"},
{"name":"Horta","description":"Portugal"},
{"name":"Dingli","description":"Malta"},
{"name":"Bangko","description":"Indonesia"},
{"name":"Jinshi","description":"China"},
{"name":"Aquin","description":"Haiti"},
{"name":"Taiping","description":"China"},
{"name":"Panghadangan","description":"Indonesia"},
{"name":"Jand","description":"Pakistan"},
{"name":"Stefanavíkion","description":"Greece"},
{"name":"El Puerto","description":"Dominican Republic"},
{"name":"Perovo","description":"Russia"},
{"name":"Banayoyo","description":"Philippines"},
{"name":"Mayang","description":"China"},
{"name":"Jieheshi","description":"China"},
{"name":"Talca","description":"Chile"},
{"name":"Bajera","description":"Indonesia"},
{"name":"Solo","description":"Philippines"}]